[package]
name = "redis-auth-filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "plugin"
crate-type = ["cdylib"]

[dependencies]
proxy-wasm = "0.2.0"
log = "0.4"
primes = "0.3.0"
redis = "0.21.5"